  <?php
    $_helper                    = $this->helper('catalog/output');
    $featured_products          = $this->getFeatured();
    //$initially_featured_product = $this->getInitiallyFeaturedProduct();
  ?>

  <div id="homepage_header_wrapper" class="outer_wrapper">
    <div id="homepage_header">
      <div class="inner_wrapper clearfix">
        <section id="homepage_center_stage">
          <ul id="steps" class="clearfix">

<?php /* TODO: This might be added back in later
            <?php foreach ($initially_featured_product as $_product): ?>
              <li class="hidden">
                <a href="#initially_featured_product"
                   rel="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->keepFrame(false)->keepAspectRatio(true)->resize(1150,null); ?>"
                ></a>
              </li>
            <?php endforeach ?>
*/ ?>

            <?php $i=1; foreach ($featured_products as $_product): ?>
              <li<?php if ($i == 3) { echo ' class="last"'; } ?>>
                <a href="#featured_product_<?php echo $i ?>"
                   rel="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->keepFrame(false)->keepAspectRatio(true)->resize(1150,null); ?>"
                   <?php if ($i == 1) { echo ' class="active"'; } ?>>
                   <?php echo $i ?>
                </a>
              </li>
            <?php $i++; endforeach; ?>
          </ul>

<?php /* TODO: This might be added back in later
          <?php foreach ($initially_featured_product as $_product): ?>
            <div id="initially_featured_product_text" class="featured_product_text active">
              <?php
                // Try to account for a 3 line name by adjusting the font size
                $name      = $_helper->productAttribute($_product, $_product->getName(), 'name');
                $font_size = strlen($name) >= 20 ? ' class="three_line"' : '';

                echo "<h1{$font_size}>{$name}</h1>";
              ?>
              <p class="content"><?php echo $_helper->productAttribute($_product, $_product->getShortDescription()) ?></p>
            </div>
          <?php endforeach ?>
*/ ?>

          <?php $i=1; foreach ($featured_products as $_product): ?>
            <div id="featured_product_<?php echo $i ?>_text" class="featured_product_text">

<?php /* TODO: This might be added back in later
              <div class="ribbon_red">
                <a href="<?php echo $_product->getProductUrl() ?>" class="amount">
                  <?php echo (int)Mage::getModel('cataloginventory/stock_item')->loadByProduct($_product)->getQty(); ?>
                </a> available
              </div>
*/ ?>
<?php /* TODO: This might be added back in later
              <?php if (Mage::getSingleton('customer/session')->isLoggedIn()): ?>
                <a href="<?php echo $this->getAddToCartUrl($_product) ?>" class="ribbon_white"><div class="add_to_cart"></div></a>
              <?php endif; ?>
*/ ?>
              <?php
                // Link to product or status/purgatory lightbox?
                $roleId        = Mage::getSingleton('customer/session')->getCustomerGroupId();
                $not_logged_in = !$this->helper('customer')->isLoggedIn()                  || isset($_GET['show_status_warning'])    ? true : false;
                $in_purgatory  = ($roleId == 4 && $this->helper('customer')->isLoggedIn()) || isset($_GET['show_purgatory_warning']) ? true : false;
                $should_hijack = $in_purgatory || $not_logged_in ? true : false;
                $the_link      = null;
                if ($not_logged_in) { $the_link = '#lightbox-signup-or-login'; }
                if ($in_purgatory)  { $the_link = '#lightbox-purgatory'; }
                $the_link      = $the_link === null ? $_product->getProductUrl() : $the_link;
                $extra_class   = $should_hijack ? ' lightbox-modal-link' : '';

                // Try to account for a 3 line name by adjusting the font size
                $name      = $_helper->productAttribute($_product, $_product->getName(), 'name');
                $font_size = strlen($name) >= 20 ? ' class="three_line"' : '';
                $font_size = strlen($name) > 20  ? ' class="three_plus_lines"' : '';

                echo "<h1{$font_size}>{$name}</h1>";
              ?>
              <p class="content"><?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?></p>
              <a class="event_details_link" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
                view event details >
              </a>
            </div>
          <?php $i++; endforeach; ?>
        </section>
      </div>
    </div>
  </div>
