  <?php $_helper = $this->helper('catalog/output'); ?>
<section id="more_events" class="section">
  <h2>more events</h2>
  <ul class="event_grid basic_grid clearfix">
  <?php foreach ($this->getMoreevents() as $_product): ?>
      <li class="item">
          <div class="ribbon_red">
            <a href="<?php echo $_product->getProductUrl() ?>" class="amount">
              <?php echo (int)Mage::getModel('cataloginventory/stock_item')->loadByProduct($_product)->getQty(); ?>
            </a> available
          </div>
          <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->keepFrame(false)->resize(308,128); ?>" width="308" height="128" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
          <h3><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h3>
          <p><?php echo $_helper->productAttribute($_product, $_product->getShortDescription()) ?></p>
          <a class="button_ribbon" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">view event</a>
      </li>
  <?php endforeach; ?>
  </ul>
</section>
