<?php
/**
 * Advance Testimonial extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   FME
 * @package    Advance Testimonial
 * @author     Kamran Rafiq Malik <support@fmeextensions.com>
 *             1- Created - 10-10-2010
 *             
 * 	       Asif Hussain <support@fmeextensions.com>
 * 	       1 - Theme - 23-03-2012
 * 	       2 - Prototype effects - 23-03-2012
 * 	       
 * @copyright  Copyright 2012 © www.fmeextensions.com All right reserved
 */
?>



<?php

/*Is Customer allowed to add testimonials */
$allwed_customer =  Mage::helper('testimonial')->getCustomerAllowed();

$form_open_option = Mage::getStoreConfig('testimonial/add_testimonial_settings/open_form');
?>

<?php if( $allwed_customer == 'guests' || ($allwed_customer == 'registered' && Mage::helper('customer')->isLoggedIn())): ?>

	    <?php if($form_open_option == 'popup'):?>
		<div class="add_button">
		    <a href="#" title="<?php echo Mage::helper('testimonial')->__('Add Testimonials') ?>" onclick="Modalbox.show($('addForm'), {title: this.title, width: 700}); return false;">
			<img src="<?php echo $this->getSkinUrl('')?>images/testimonial/testimonials_button.png" class="btn_right" alt=" " border="0" />
		    </a>
		</div><br />
	    <?php elseif($form_open_option == 'slide'): ?>
	    
	    <script type='text/javascript'>	    
		function SDEffect(element){   new Effect.SlideDown(element, {duration:2}); $('slideup_arrow').show(); $('slidedown_btn').hide(); }
	        
		function SUEffect(element){   new Effect.SlideUp(element, {duration:2}); $('slideup_arrow').hide();  $('slidedown_btn').show(); }
	    </script>
	    
	    <div class="add_button">
		    
		    <a href="#" title="<?php echo Mage::helper('testimonial')->__('Add Testimonials') ?>" onclick="SDEffect('addForm');">
			<img src="<?php echo $this->getSkinUrl('')?>images/testimonial/testimonials_button.png" class="btn_right" id="slidedown_btn" alt=" " border="0" />
		    </a>
		    
	    </div><br />
	    
	    
	    <?php else :?>
	    
		<div class="add_button">
		    <a href="<?php echo $this->getUrl('*/*/add'); ?>" title="<?php echo Mage::helper('testimonial')->__('Add Testimonials') ?>">
			<img src="<?php echo $this->getSkinUrl('')?>images/testimonial/testimonials_button.png" class="btn_right" alt=" " border="0" />
		    </a>
		</div><br />
	    
	    <?php endif; ?>
	    



<?php endif; ?>













<!--/////////////////////TESTIMONIAL FORM ///////////////////////////-->


<div id="addForm" class="popupForm" style="display:none;">
    
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>

<form action="<?php echo Mage::getUrl('*/*/post') ?>" id="testimonialForm" name="testimonialForm" method="post" enctype="multipart/form-data">

<?
	$value = 0;
	$status = Mage::helper('testimonial')->getAdminApproval();
	if($status == 0) {
		$value = 1;
	} elseif($status == 1) {
		$value = 0;
	} else {
		$value = 0;
	}


?>
        
<input name="status" id="status" value="<?php echo $value; ?>" type="hidden"  />
		
        <input name="stores[]" id="stores[]" value="<?php echo Mage::app()->getStore()->getStoreId(); ?>" type="hidden"  />

        <div class="fieldset">
        <h2 class="legend"><?php echo Mage::helper('testimonial')->__('Testimonial Information') ?></h2>
        <ul class="form-list">
            <li class="fields">
            	<?php 
					if(Mage::getStoreConfig('testimonial/formfields/company_name')) {
				?>
                <div class="field">
                    <label for="company_name"><?php echo Mage::helper('testimonial')->__('Company') ?></label>
                    <div class="input-box">
                    <input name="company_name" id="company_name" title="<?php echo Mage::helper('testimonial')->__('Company Name ') ?>" value="" class="input-text" type="text" />
                    </div>
                </div>
                <?php } ?>
                <?php 
					if(Mage::getStoreConfig('testimonial/formfields/contact_name')) {
				?>
                <div class="field">
                    <label for="contact_name"><?php echo Mage::helper('testimonial')->__('Contact Name') ?></label>
                    <div class="input-box">
                        <input name="contact_name" id="contact_name" title="<?php echo Mage::helper('contacts')->__('Contact Name') ?>" value="<?php echo $this->htmlEscape($this->helper('contacts')->getUserName()) ?>" class="input-text" type="text" />
                    </div>
                </div>
                <?php } ?>
            </li>
            
            <li class="fields">
            	<?php 
					if(Mage::getStoreConfig('testimonial/formfields/email')) {
				?>
                <div class="field">
                    <label for="email" class="required"><em>*</em><?php echo Mage::helper('testimonial')->__('Email') ?></label>
                    <div class="input-box">
                    <input name="email" id="email" title="<?php echo Mage::helper('testimonial')->__('Email') ?>" value="<?php echo $this->htmlEscape($this->helper('testimonial')->getUserEmail()) ?>" class="input-text required-entry validate-email" type="text" />
                    </div>
                </div>
                <?php } ?>
                <?php 
					if(Mage::getStoreConfig('testimonial/formfields/website')) {
				?>
                <div class="field">
                    <label for="website"><?php echo Mage::helper('testimonial')->__('Website URL') ?></label>
                    <div class="input-box">
                        <input name="website" id="website" title="<?php echo Mage::helper('testimonial')->__('Website URL') ?>" value="" class="input-text validate-clean-url" type="text" />
                    </div>
                </div>
                <?php } ?>
            </li>
            
	    <!--Custom Fields Start-->
	    
	    <li class="fields">
		
		<?php $custom_field1_label = Mage::getStoreConfig('testimonial/form_custom_field/field1_label'); ?>
            	<?php if(Mage::getStoreConfig('testimonial/form_custom_field/field1_status') && $custom_field1_label != ''){ ?>
                <div class="field">
                    <label for="custom_field1_value" ><?php echo Mage::helper('testimonial')->__($custom_field1_label) ?></label>
                    <div class="input-box">
			<input name="custom_field1_value" id="custom_field1_value" title="<?php echo Mage::helper('testimonial')->__($custom_field1_label) ?>" value="" class="input-text" type="text" />
                    </div>
                </div>
                <?php } ?>
		
		
		<?php $custom_field2_label = Mage::getStoreConfig('testimonial/form_custom_field/field2_label'); ?>
                <?php if(Mage::getStoreConfig('testimonial/form_custom_field/field2_status') && $custom_field2_label != null){ ?>
                <div class="field">
                    <label for="custom_field2_value"><?php echo Mage::helper('testimonial')->__($custom_field2_label) ?></label>
                    <div class="input-box">
                        <input name="custom_field2_value" id="custom_field2_value" title="<?php echo Mage::helper('testimonial')->__($custom_field2_label) ?>" value="" class="input-text" type="text" />
                    </div>
                </div>
                <?php } ?>
            </li>
	    
	    
	    <li class="fields">
		
		<?php $custom_field3_label = Mage::getStoreConfig('testimonial/form_custom_field/field3_label'); ?>
            	<?php if(Mage::getStoreConfig('testimonial/form_custom_field/field3_status') && $custom_field3_label != ''){ ?>
                <div class="field">
                    <label for="custom_field3_value" ><?php echo Mage::helper('testimonial')->__($custom_field3_label) ?></label>
                    <div class="input-box">
			<input name="custom_field3_value" id="custom_field3_value" title="<?php echo Mage::helper('testimonial')->__($custom_field3_label) ?>" value="" class="input-text" type="text" />
                    </div>
                </div>
                <?php } ?>
		
		
		<?php $custom_field4_label = Mage::getStoreConfig('testimonial/form_custom_field/field4_label'); ?>
                <?php if(Mage::getStoreConfig('testimonial/form_custom_field/field4_status') && $custom_field4_label != null){ ?>
                <div class="field">
                    <label for="custom_field4_value"><?php echo Mage::helper('testimonial')->__($custom_field4_label) ?></label>
                    <div class="input-box">
                        <input name="custom_field4_value" id="custom_field4_value" title="<?php echo Mage::helper('testimonial')->__($custom_field4_label) ?>" value="" class="input-text" type="text" />
                    </div>
                </div>
                <?php } ?>
            </li>
	    
	    
	    
	    
	    <!--Custom Fields End-->
	    <?php
		$short_desc_req = false;
		if(Mage::getStoreConfig('testimonial/list/allow_read_more') == 1 || Mage::getStoreConfig('testimonial/featuredtestimonials/allow_read_more') == 1):
		    $short_desc_req = true;
		else:
		    $short_desc_req = false;
		endif;
	    ?>
	    
	    <?php if(Mage::getStoreConfig('testimonial/formfields/short_desc')): ?>
	    <li class="wide">
                <label for="short_description" class="required"><?php if($short_desc_req): ?><em>*</em><?php endif; ?><?php echo Mage::helper('testimonial')->__('Short Description') ?></label>
                <div class="input-box">
                    <textarea name="short_description" id="short_description" title="<?php echo Mage::helper('testimonial')->__('Short Description') ?>" class="<?php if($short_desc_req): ?>required-entry<?php endif; ?> input-text" cols="3" rows="2"></textarea>
                </div>
            </li>
	    <?php endif; ?>
	    
            <li class="wide">
                <label for="testimonial" class="required"><em>*</em><?php echo Mage::helper('testimonial')->__('Testimonial') ?></label>
                <div class="input-box">
                    <textarea name="testimonial" id="testimonial" title="<?php echo Mage::helper('testimonial')->__('Testimonial') ?>" class="required-entry input-text" cols="5" rows="3"></textarea>
                </div>
            </li>
	    
	    
		
            	<?php 	if(Mage::getStoreConfig('testimonial/formfields/contact_photo')) { ?>
					    
				
				<li>
		
				<label for="testimonial" class="required"><?php echo Mage::helper('testimonial')->__('Upload Contact Photo :') ?></label>
					
				<?php
				
				$flash_uploader_path = Mage::getModuleDir('Helper','FME_Testimonial');
				require_once($flash_uploader_path."/Helper/class.FlashUploader.php");
				
				IAF_display_js();
				$uploader = new FlashUploader('uploader', $this->getJsUrl('testimonial/flash_uploader/uploader'),Mage::getUrl('*/*/flashupload'));
				$uploader->display();
				
				
				?>
				
				
					<input name="ajax_form" id="ajax_form" value="yes" class="input-text" type="hidden" />
				</li>
				
                 <?php } ?>
		 
		 
            
	    
	    
            <li class="wide"> 
			    <input name="captacha_code" type="hidden" id="captacha_code" value="<?php echo $code=$this->getNewrandCode(6)?>" />
			    <label for="image"><img src="<?php echo $this->getSecureImageUrl() ?>CaptchaSecurityImages.php?width=180&height=40&code=<?php echo $code?>" /></label><br/>
			    <div class="input-box">
				<label for="security_code" class="required"><em>*</em><b><?php echo $this->__('Security Code Message:'); ?></b></label><br />
				<input class="required-entry" id="security_code" name="security_code" type="text" /> <br />
				<?php echo $this->__('If you have difficulty in reading the image above then refresh your browser a few times until you see an image that is clear enough to copy.'); ?>
			
			    </div> 
	    </li>
	    
	    
	    
        </ul>
        </div>
        <div class="buttons-set">
	    
	    <a href="#" title="<?php echo Mage::helper('testimonial')->__('Close Form') ?>" onclick="SUEffect('addForm');" >
			<img src="<?php echo $this->getSkinUrl('')?>images/testimonial/close.gif" class="slideup_arrow" id="slideup_arrow" alt="Close Form" style="display:none;" border="0" />
	    </a>
	
	    <p id="progress_loader"><img src="<?php echo $this->getSkinUrl('images/testimonial/loader.gif')?>" /></p>
	    
            <p class="required"><?php echo Mage::helper('testimonial')->__('* Required Fields') ?></p>
            <input type="text" name="hideit" id="hideit" value="" style="display:none !important;" />
            
	    <button  onclick="saveTestimonialForm()"  type="button" title="<?php echo Mage::helper('testimonial')->__('Submit') ?>" class="button"><span><span><?php echo Mage::helper('contacts')->__('Submit') ?></span></span></button>
        
	</div>
	
	
</form>


<div class="clear"></div>

</div>



<!--ALL TEST-------------------------------------->

<div class="myBox">
    
  <p class="heading_1"><?php echo Mage::helper('testimonial')->getListPageTitle(); ?></p>
  	<?php $collection = $this->getItems(); ?>
	<?php if ( count($collection) == 0 ) : ?>
	    <p class="text_1"><?php echo $this->__('No testimonial yet...'); ?></p>
	<?php else : ?>
	



<!--Theme1 Starts	-->
<?php if(Mage::getStoreConfig('testimonial/themes/select_theme') == 'theme1'): ?>

	<?php foreach ( $collection as $_item ) : ?> 	
	    
	    <div class="theme1">
		<div class="testimonial">
		    
			<?php
					if($_item["contact_photo"] != "") {
					    
						$filename = Mage::getBaseDir('media')."/testimonials/".$_item["testimonial_id"]."/".$_item["contact_photo"];
						if (file_exists($filename)) {
							$imgURL = Mage::getBaseUrl('media')."/testimonials/".$_item["testimonial_id"]."/".$_item["contact_photo"];
						} else {
							$imgURL = Mage::getBaseUrl('media')."testimonials/no_image.jpg";
						}
					} else {
						$imgURL = Mage::getBaseUrl('media')."testimonials/no_image.jpg";
					} 
			?>
			
			<?php
				if($_item['url_identifier'] != ''): 
				    $testimonial_url = Mage::helper('testimonial')->getListIdentifier().'/'.$_item['url_identifier'].Mage::helper('testimonial')->getSeoUrlSuffix();
				else:
				    $testimonial_url = Mage::getUrl('*/*/detail',array('id' => $_item["testimonial_id"]));
				endif;
			
			?>
			
			<?php if(Mage::getStoreConfig('testimonial/list/allow_read_more')): ?>
			    
			    <!--SHORT DESCRIPTION GOES THERE-->
			    <p><img src="<?php echo $this->getSkinUrl('')?>images/testimonial/quote1.png" class="quote1"/><?php echo stripslashes($_item['short_description']); ?><a href="<?php echo $testimonial_url; ?>" class="read_more"><?php echo $this->__('Read More'); ?> </a><img src="<?php echo $this->getSkinUrl('')?>images/testimonial/quote2.png" class="quote2" style="clear:both;"/></p><br />
			    
			<?php else: ?>
			    
			    <!--FULL DESCRIPTION GOES THERE-->
			    <p><img src="<?php echo $this->getSkinUrl('')?>images/testimonial/quote1.png" class="quote1"/><?php echo stripslashes($_item['testimonial']); ?><img src="<?php echo $this->getSkinUrl('')?>images/testimonial/quote2.png" class="quote2"/></p>
			  
			<?php endif; ?>
			
			
		    
			<?php if(Mage::getStoreConfig('testimonial/list/show_contact_photo')) { ?>
			
			<div class="testi-pic">
			    <img src="<?php echo $imgURL; ?>"  alt=" " border="none" width="75" height="75" />
			</div>
			
			<?php } ?>
			
			
			
			
			<div class="testi-name">
			    <strong><?php echo $_item['contact_name']; ?></strong> <br />
			    <?php echo $_item['company_name']; ?>
			</div>
			<div class="clear"></div>
			
		</div>
	    </div>
	    <div class="clear"></div>	 
	    
  	<?php endforeach; ?>
	

<!--Theme1 Ends	-->


<!--Theme2 Starts	-->
<?php elseif(Mage::getStoreConfig('testimonial/themes/select_theme') == 'theme2'): ?>
	
	<div class="theme2">
	<?php foreach ( $collection as $_item ) : ?> 	
	    
	    <div class="testimonial2">
		<div class="inner">
		    
			<?php
					if($_item["contact_photo"] != "") {
					    
						$filename = Mage::getBaseDir('media')."/testimonials/".$_item["testimonial_id"]."/".$_item["contact_photo"];
						if (file_exists($filename)) {
							$imgURL = Mage::getBaseUrl('media')."/testimonials/".$_item["testimonial_id"]."/".$_item["contact_photo"];
						} else {
							$imgURL = Mage::getBaseUrl('media')."testimonials/no_image.jpg";
						}
					} else {
						$imgURL = Mage::getBaseUrl('media')."testimonials/no_image.jpg";
					} 
			?>
			
			<?php if(Mage::getStoreConfig('testimonial/list/show_contact_photo')) { ?>
			
			<div class="thumbnail">
			    <img src="<?php echo $imgURL; ?>"  alt=" " border="none" width="75" height="75" />
			</div>
			
			<?php } ?>
			
			<div class="content">
			
			
				    <?php
					    if($_item['url_identifier'] != ''): 
						$testimonial_url = Mage::helper('testimonial')->getListIdentifier().'/'.$_item['url_identifier'].Mage::helper('testimonial')->getSeoUrlSuffix();
					    else:
						$testimonial_url = Mage::getUrl('*/*/detail',array('id' => $_item["testimonial_id"]));
					    endif;
				    
				    ?>
				    
				    <?php if(Mage::getStoreConfig('testimonial/list/allow_read_more')): ?>
					
					<!--SHORT DESCRIPTION GOES THERE-->
					<div class="content_inner">
					    <img src="<?php echo $this->getSkinUrl('')?>images/testimonial/left_coma.png"  width="34" height="22" class="left"/>
						<?php echo stripslashes($_item['short_description']); ?>
					    <img src="<?php echo $this->getSkinUrl('')?>images/testimonial/right_coma.png"  width="34" height="22" class="right_coma" />
						<a href="<?php echo $testimonial_url; ?>" class="read_more"><?php echo $this->__('Read More'); ?> </a>
					</div>
				    <?php else: ?>
					
					<!--FULL DESCRIPTION GOES THERE-->
					<div class="content_inner">
					    <img src="<?php echo $this->getSkinUrl('')?>images/testimonial/left_coma.png"  width="34" height="22" class="left" />
					    <?php echo stripslashes($_item['testimonial']); ?>
					    <img src="<?php echo $this->getSkinUrl('')?>images/testimonial/right_coma.png"  width="34" height="22" class="right_coma" />
					</div>
				    <?php endif; ?>
				    
				    
				
				    
				    <h4><b><?php echo $_item['contact_name']; ?></b>&#44; <?php echo $_item['company_name']; ?></h4>
				    <div class="clear"></div>
				    
			</div>
			
		</div>
		<div class="clear"></div>
	    </div>
	    	 
	    
  	<?php endforeach; ?>
	</div>
	<!--Theme2 Ends	-->
	
	
	
<!--Theme3 Starts	-->
<?php elseif(Mage::getStoreConfig('testimonial/themes/select_theme') == 'theme3'): ?>
	
	<div class="theme3">
	<?php foreach ( $collection as $_item ) : ?> 	
	    
	    <div class="testimonial3">
		
		    
			<?php
					if($_item["contact_photo"] != "") {
					    
						$filename = Mage::getBaseDir('media')."/testimonials/".$_item["testimonial_id"]."/".$_item["contact_photo"];
						if (file_exists($filename)) {
							$imgURL = Mage::getBaseUrl('media')."/testimonials/".$_item["testimonial_id"]."/".$_item["contact_photo"];
						} else {
							$imgURL = Mage::getBaseUrl('media')."testimonials/no_image.jpg";
						}
					} else {
						$imgURL = Mage::getBaseUrl('media')."testimonials/no_image.jpg";
					} 
			?>
			
			
			
			<div class="client">
			    <?php if(Mage::getStoreConfig('testimonial/list/show_contact_photo')) { ?>
				<div class="thumb">
				    <img src="<?php echo $imgURL; ?>"  alt=" " border="none" width="75" height="75" />
				</div>
			    <?php } ?>
			    
				<p><?php echo $_item['contact_name']; ?></p>
			    	<?php echo $_item['company_name']; ?>
			    
			</div>
			
			
			
			
			<div class="detail">
			
			
				    <?php
					    if($_item['url_identifier'] != ''): 
						$testimonial_url = Mage::helper('testimonial')->getListIdentifier().'/'.$_item['url_identifier'].Mage::helper('testimonial')->getSeoUrlSuffix();
					    else:
						$testimonial_url = Mage::getUrl('*/*/detail',array('id' => $_item["testimonial_id"]));
					    endif;
				    
				    ?>
				    
				    <?php if(Mage::getStoreConfig('testimonial/list/allow_read_more')): ?>
					
					<!--SHORT DESCRIPTION GOES THERE-->
					<div class="content_inner">
					    <img src="<?php echo $this->getSkinUrl('')?>images/testimonial/left_coma.png"  width="34" height="22" class="left_coma" />
					    <?php echo stripslashes($_item['short_description']); ?>
					    <img src="<?php echo $this->getSkinUrl('')?>images/testimonial/right_coma.png"  width="34" height="22" class="right_coma" />
						<a href="<?php echo $testimonial_url; ?>" class="read_more"><?php echo $this->__('Read More'); ?> </a>
					</div>
				    <?php else: ?>
					
					<!--FULL DESCRIPTION GOES THERE-->
					<div class="content_inner">
					    <img src="<?php echo $this->getSkinUrl('')?>images/testimonial/left_coma.png"  width="34" height="22" class="left_coma" />
					    <?php echo stripslashes($_item['testimonial']); ?>
					    <img src="<?php echo $this->getSkinUrl('')?>images/testimonial/right_coma.png"  width="34" height="22" class="right_coma" />
					</div>
				    <?php endif; ?>
				    
				    
				 
			</div>
			
		
		<div class="clear"></div>
	    </div>
	    	 
	    
  	<?php endforeach; ?>
	</div>
<!--Theme3 Ends	-->


<!--Theme4 Starts	-->
<?php elseif(Mage::getStoreConfig('testimonial/themes/select_theme') == 'theme4'): ?>
	
	<div class="theme4">
	<?php foreach ( $collection as $_item ) : ?> 	
	    
	    <div class="testimonial4">
		
		    
			<?php
					if($_item["contact_photo"] != "") {
					    
						$filename = Mage::getBaseDir('media')."/testimonials/".$_item["testimonial_id"]."/".$_item["contact_photo"];
						if (file_exists($filename)) {
							$imgURL = Mage::getBaseUrl('media')."/testimonials/".$_item["testimonial_id"]."/".$_item["contact_photo"];
						} else {
							$imgURL = Mage::getBaseUrl('media')."testimonials/no_image.jpg";
						}
					} else {
						$imgURL = Mage::getBaseUrl('media')."testimonials/no_image.jpg";
					} 
			?>
			
			
			
			<div class="client">
			    <?php if(Mage::getStoreConfig('testimonial/list/show_contact_photo')) { ?>
				<div class="thumb">
				    <img src="<?php echo $imgURL; ?>"  alt=" " border="none" width="75" height="75" />
				</div>
			    <?php } ?>
			    
				   
			</div>
			
			
			
			
			<div class="detail">
			
				    <img class="arrow" alt="" src="<?php echo $this->getSkinUrl('images/testimonial/testi_arrow.png'); ?>">
					
				    <?php
					    if($_item['url_identifier'] != ''): 
						$testimonial_url = Mage::helper('testimonial')->getListIdentifier().'/'.$_item['url_identifier'].Mage::helper('testimonial')->getSeoUrlSuffix();
					    else:
						$testimonial_url = Mage::getUrl('*/*/detail',array('id' => $_item["testimonial_id"]));
					    endif;
				    
				    ?>
				    
				    <?php if(Mage::getStoreConfig('testimonial/list/allow_read_more')): ?>
					
					<!--SHORT DESCRIPTION GOES THERE-->
					<div class="content_inner">
					    <?php echo stripslashes($_item['short_description']); ?><a href="<?php echo $testimonial_url; ?>" class="read_more"><?php echo $this->__('Read More'); ?> </a>
					    <b><?php echo $_item['contact_name']; ?> &#45; <?php echo $_item['company_name']; ?></b>
					</div>
					
				    <?php else: ?>
					
					<!--FULL DESCRIPTION GOES THERE-->
					<div class="content_inner">
					    
					    <?php echo stripslashes($_item['testimonial']); ?>
					    
					    <b><?php echo $_item['contact_name']; ?> &#45; <?php echo $_item['company_name']; ?></b>
					</div>
				    <?php endif; ?>
				    
				    
				 
			</div>
			
		
		<div class="clear"></div>
	    </div>
	    	 
	    
  	<?php endforeach; ?>
	</div>
<!--Theme4 Ends	-->
	
	
	
<?php endif; ?>



	
	
  
  	<?php /* Pagination control */ ?>
	<?php if ( $collection instanceof Zend_Paginator ) : ?>
		<?php echo $this->getChildHtml('pagination'); ?>
	<?php endif; ?>
	<?php echo $this->getChildHtml('toolbar'); ?>
	<?php endif; ?>
</div>





<script type="text/javascript">
   
    //form posting
    
    function saveTestimonialForm(){
	
	
	
	var bookafittingForm = new VarienForm('testimonialForm', true);
	
	//validate the captcha code
	var t_form = $('testimonialForm');
	var captcha_code = Form.Element.getValue(t_form['captacha_code']); //Hidden field,real code
	var security_code = Form.Element.getValue(t_form['security_code']);
	
	if(security_code != '' && captcha_code != security_code){
	    
	    alert('<?php echo $this->__('Captcha Code is not Correct'); ?>');
	    return false;
	}
	
	
	
	 //if the form is valid
	if(bookafittingForm.validator.validate()) {
	    
	    $('testimonialForm').request({
		    
		    method: 'post',
		    onLoading:function(transport){
			
			    $('progress_loader').setStyle({display:'block'});
			},
		    onSuccess: function(transport){
			    transport.responseText;
			    alert('<?php echo $this->__('Your Testimonial added successfully'); ?>');
			    $('progress_loader').setStyle({display:'none'});
			    
			    Modalbox.hide($('addForm'));
			    SUEffect('addForm');
			    
			},
		    onFailure: function(transport){
			    alert('<?php echo $this->__('Sorry, Error found try again later'); ?>');
			    $('progress_loader').setStyle({display:'none'});
			    Modalbox.hide($('addForm'));
		    }
		    
		});
	    
	    
	    
	       
	}
	
	
    }
    
    
</script>

