  <?php
    $_helper                    = $this->helper('catalog/output');
    $catid						= (isSet($_GET['cid']) ? $_GET['cid'] : 0);
    $featured_products          = $this->getInitiallyFeaturedProduct($catid);
    //$initially_featured_product = $this->getInitiallyFeaturedProduct();
    
/*
    $Mage_Catalog_Block_Navigation = new Mage_Catalog_Block_Navigation();
$categories = $Mage_Catalog_Block_Navigation->getStoreCategories();

function render_flat_nav($categories) {
    $html = '<ul>';
    foreach($categories as $category) {
        $html .= '<li><a href="' . $category->getCategoryUrl($cat) . '">' . 
                  $category->getName() . "</a>\n - ". $category->getID();
        if($category->hasChildren()) {
            $children = Mage::getModel('catalog/category')->getCategories($category->entity_id);
            $html .= render_flat_nav($children);
            }
        $html .= '</li>';
    }
    return $html . '</ul>';
}
echo render_flat_nav($categories); 
*/
?>

<div id="homepage_body_wrapper" class="outer_wrapper">
	<div id="homepage_body">
		<div class="inner_wrapper clearfix">
			<section id="eventlist_events">
				<div id="eventlist_events_header">kapow events</div>
				<a href="<?php echo Mage::getBaseUrl() ?>?" class="eventlist_events_header_link<?php echo (!isSet($_GET['cid']) ? ' header_active' : '') ?>">See All Events</a>
				<a href="<?php echo Mage::getBaseUrl() ?>?cid=15" class="eventlist_events_header_link"<?php echo (isset($_GET['cid']) && $_GET['cid'] == 15) ? ' header_active' : '' ?>>Bar Events</a>
				<a href="<?php echo Mage::getBaseUrl() ?>?cid=16" class="eventlist_events_header_link"<?php echo (isset($_GET['cid']) && $_GET['cid'] == 16) ? ' header_active' : '' ?>>Dining Events</a>
				<a href="<?php echo Mage::getBaseUrl() ?>?cid=17" class="eventlist_events_header_link"<?php echo (isset($_GET['cid']) && $_GET['cid'] == 17) ? ' header_active' : '' ?>>Sporting Events</a>
				<div id="eventlist_events_container">
					<ul>
						<?php $i=1; foreach ($featured_products as $_product): ?>
						<li id="eventlist_event_<?php echo $i ?>_text" class="eventlist_products">
							<div class="eventlist_product_info">
								<?php
								// Link to product or status/purgatory lightbox?
								$roleId        = Mage::getSingleton('customer/session')->getCustomerGroupId();
								$not_logged_in = !$this->helper('customer')->isLoggedIn()                  || isset($_GET['show_status_warning'])    ? true : false;
								$in_purgatory  = ($roleId == 4 && $this->helper('customer')->isLoggedIn()) || isset($_GET['show_purgatory_warning']) ? true : false;
								$should_hijack = $in_purgatory || $not_logged_in ? true : false;
								$the_link      = null;
								if ($not_logged_in) { $the_link = '#lightbox-signup-or-login'; }
								if ($in_purgatory)  { $the_link = '#lightbox-purgatory'; }
								$the_link      = $the_link === null ? $_product->getProductUrl() : $the_link;
								$extra_class   = $should_hijack ? ' lightbox-modal-link' : '';
								
								// Try to account for a 3 line name by adjusting the font size
								$name      		= $_helper->productAttribute($_product, $_product->getName(), 'name');
								$font_size 		= strlen($name) >= 50 ? ' three_line' : '';
								$font_size 		= strlen($name) > 50  ? ' three_plus_lines' : '';
								$group_size_min = $_product->getResource()->getAttribute('event_group_size_min')->getFrontend()->getValue($_product);
								$group_size_max = $_product->getResource()->getAttribute('event_group_size_max')->getFrontend()->getValue($_product);
                                $perPerson  = $_product->getResource()->getAttribute('per_person_cost');                                
                                
								if($group_size_max == NULL) {
									$group_size_string = "<div class=\"single\">".$group_size_min."</div>";
								}
								else {
									$group_size_string = $group_size_min . "<div>to</div>" . $group_size_max;
								}
                                
                                if (!$perPerson) {
                                    $cost = '';
                                } else {
                                    if ($perPerson && $perPerson->getFrontend()->getValue($_product) == "") {
                                        $cost 		= round($_product->getResource()->getAttribute('price')->getFrontend()->getValue($_product));
                                    }
                                    else {
                                        $cost 		= round($perPerson->getFrontend()->getValue($_product));
                                    }
                                }
								$categories		= $_product->getCategoryIds();
								$event_icons	= array("","","","","","");
								foreach ($categories as $cat) {
									if ($cat == 9)
										$event_icons[0] = " active";
									if ($cat == 14)
										$event_icons[1] = " active";
									if ($cat == 13)
										$event_icons[2] = " active";
									if ($cat == 12)
										$event_icons[3] = " active";
									if ($cat == 3)
										$event_icons[4] = " active";
									if ($cat == 10)
										$event_icons[5] = " active";
								}
								
								echo "<div class=\"product_header{$font_size}\">{$name}</div>";
								?>
								<div class="eventlist_event_image" style="background: url(<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->keepFrame(false)->keepAspectRatio(true)->resize(330,null); ?>) no-repeat;"></div>
	
								<p class="content">
									<?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
								</p>
								<div class="eventlist_event_details">
									<div id="eventlist_per_person" class="eventlist_event_detail_bubble">
										<div class="bubble_text">$<?php echo $cost ?></div>
										<div id="eventlist_per_person_tag" class="event_detail_tag">Per Person</div>
									</div>
									<div id="eventlist_group_size" class="eventlist_event_detail_bubble">
										<div class="bubble_text">
											<?php echo $group_size_string ?>
										</div>
										<div id="eventlist_group_size_tag" class="event_detail_tag">Group Size</div>
									</div>
									<div id="eventlist_ideal_for" class="eventlist_event_detail_bubble">
										<div class="minibubbles">
											<div class="minibubbles_row1">
												<div class="bubble_icon summer_outing<?php echo $event_icons[0] ?>" title="Summer Outing"></div>
												<div class="bubble_icon company_outing<?php echo $event_icons[1] ?>" title="Company Outing"></div>
												<div class="bubble_icon team_activity<?php echo $event_icons[2] ?>" title="Team Activity"></div>
											</div>
											<div class="minibubbles_row2">
												<div class="bubble_icon holiday_party<?php echo $event_icons[3] ?>" title="Holiday Party"></div>
												<div class="bubble_icon client_entertainment<?php echo $event_icons[4] ?>" title="Client Entertainment"></div>
												<div class="bubble_icon addon<?php echo $event_icons[5] ?>" title="Addon"></div>
											</div>
										</div>
										<div id="eventlist_ideal_for_tag" class="event_detail_tag">Ideal For</div>
									</div>
								</div>
								<div class="clearfix"></div>
								<div class="event_detail_bottom"></div>		
								<a class="event_details_link<?php echo $extra_class ?>" href="<?php echo $the_link ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">View Details <span>&amp; Book!</span></a>
							</div>
							<div class="event_flare"></div>
						</li>
						<?php $i++; endforeach; ?>
					</ul>
				</div>
			</section>
		</div>
		<div class="bottom_border">
			<a href="events" title="View All Events" id="view_all_events">View All Events</a>
		</div>
	</div>
</div>