  <?php
    $_helper                    = $this->helper('catalog/output');
    $featured_products          = $this->getFeatured();
    //$initially_featured_product = $this->getInitiallyFeaturedProduct();
  ?>

<div id="homepage_header_wrapper" class="outer_wrapper">
	<div id="homepage_header">
		<div class="inner_wrapper clearfix">
			<section id="featured_events">
				<ul id="steps">
					<?php $i=1; foreach ($featured_products as $_product): ?>
					<li<?php if ($i == 3) { echo ' class="last"'; } ?>>
						<a href="#featured_product_<?php echo $i ?>"
						rel="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->keepFrame(false)->keepAspectRatio(true)->resize(1150,null); ?>"
						<?php if ($i == 1) { echo ' class="active"'; } ?>>
						</a>
					</li>
					<?php $i++; endforeach; ?>
				</ul>
				<?php $i=1; foreach ($featured_products as $_product): ?>
					<div id="featured_product_<?php echo $i ?>_text" class="featured_product_text">
						<div class="event_darken"></div>
						<div class="product_info">
							<?php
							// Link to product or status/purgatory lightbox?
							$roleId        = Mage::getSingleton('customer/session')->getCustomerGroupId();
							$not_logged_in = !$this->helper('customer')->isLoggedIn()                  || isset($_GET['show_status_warning'])    ? true : false;
							$in_purgatory  = ($roleId == 4 && $this->helper('customer')->isLoggedIn()) || isset($_GET['show_purgatory_warning']) ? true : false;
							$should_hijack = $in_purgatory || $not_logged_in ? true : false;
							$the_link      = null;
							if ($not_logged_in) { $the_link = '#lightbox-signup-or-login'; }
							if ($in_purgatory)  { $the_link = '#lightbox-purgatory'; }
							$the_link      = $the_link === null ? $_product->getProductUrl() : $the_link;
							$extra_class   = $should_hijack ? ' lightbox-modal-link' : '';
							
							// Try to account for a 3 line name by adjusting the font size
                            $ribbon         = $_product->getResource()->getAttribute('ribbon_title');
							$name      		= ($ribbon && $ribbon->getFrontend()->getValue($_product) != "" ? $ribbon->getFrontend()->getValue($_product) : $_helper->productAttribute($_product, $_product->getName(), 'name'));
							$font_size 		= strlen($name) >= 50 ? ' three_line' : '';
							$font_size 		= strlen($name) > 50  ? ' three_plus_lines' : '';
							$group_size_min = $_product->getResource()->getAttribute('event_group_size_min')->getFrontend()->getValue($_product);
							$group_size_max = $_product->getResource()->getAttribute('event_group_size_max')->getFrontend()->getValue($_product);
							$cost			= $_product->getAttributeText('event_cost_size');
                            $perPerson  = $_product->getResource()->getAttribute('per_person_cost');
							if ($group_size_min == "") {
								$group_size_string = $group_size_max;
							}
							elseif($group_size_max == "") {
								$group_size_string == $group_size_min;
							}
							else {
								$group_size_string = $group_size_min . " - " . $group_size_max;
							}
							if ($not_logged_in) {
                                    $cost = $_product->getAttributeText('event_cost_size');;
                            } else {
                                if ($perPerson && $perPerson->getFrontend()->getValue($_product) == "") {
                                    $cost 		= "$".round($_product->getResource()->getAttribute('price')->getFrontend()->getValue($_product));
                                }
                                else if($perPerson) {
                                    $cost 		= "$".round($perPerson->getFrontend()->getValue($_product));
                                }
                            }
                            
                            $linkstatus1 = 'class="get_started';
						    $linkstatus1 .= $extra_class . '" ';
						    $linkstatus1 .= 'href="'.$the_link.'"';
						    $linkstatus1 .= ($not_logged_in ? ' rev="'.Mage::helper('core')->urlEncode($_product->getProductUrl()).'"' : '');

						    $linkstatus2 = 'class="event_details_link';
						    $linkstatus2 .= $extra_class . '" ';
						    $linkstatus2 .= 'href="'.$the_link.'"';
						    $linkstatus2 .= ($not_logged_in ? ' rev="'.Mage::helper('core')->urlEncode($_product->getProductUrl()).'"' : '');
						    
						     $trackClick = ($not_logged_in ? "onclick=\"_gaq.push(['_trackEvent', 'Event Click', 'Modal PopUp - Buy Now Link', '$name']);\"" : "");
							
							echo "<div class=\"product_header{$font_size}\">{$name}</div>";
							
							/*?>
							<p class="content">
								<?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
							</p>
							*/
							?>
							<div class="event_details_info" id="event_detail_cost">
								Cost - <?php echo $cost; ?>
								<a <?php echo $linkstatus2 ?> title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" <?php echo $trackClick ?>>Buy Now &gt;</a>
							</div>
							<div class="event_details_info" id="event_detail_group">
								Group Size - <?php echo $group_size_string ?>
							</div>
						</div>
						
						<div class="event_flare"></div>
					</div>
				<?php $i++; endforeach; ?>
			</section>
			<section id="homepage_center_stage">
				<div id="testimonial">
					<div id="openquote" class="quoteimage"></div>
                    <?php echo $this->getLayout()->createBlock('testimonial/block')->setTemplate('testimonial/block.phtml')->toHtml(); ?>
					<div id="closequote" class="quoteimage"></div>
				</div>
				<div id="statement">
					<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('header_sell_statement')->toHtml() ?> 
				</div>
				<a <?php echo $linkstatus1 ?> id="get_started" title="Get Started" onclick="_gaq.push(['_trackEvent', 'Get Started Click', 'Modal PopUp - Get Started', 'Get Started']);">Get Started &gt;</a>
			</section>
		</div>
	</div>
</div>