	</div>
</div>
<div id="cut_splitter"></div>
<div id="recent_success">
	<div id="success_container">
		<h2>Recent News</h2>
		<div id="followus">
			Follow Us On
		</div>
		<div id="followusarrow"></div>
		<a href="https://twitter.com/kapowchicago" class="twitter_findus social_findus"></a>
		<a href="https://www.facebook.com/KapowChicago" class="facebook_findus social_findus"></a>
		<div id="dateinfo">
			<?php echo date('F d, Y'); ?>
			<div id="kapowissue">
			</div>
		</div>
	</div>
    <?php echo $this->getChildHtml('recent_posts') ?>
    <div class="clearfix"></div>
    <div id="success_bottom">
		<a href="/blog" title="View All News" id="viewallnews">View All News</a>
    </div>    
</div>
<div>
	<div>
