<?php
/**
 * @category    Fishpig
 * @package     Fishpig_Wordpress
 * @license     http://fishpig.co.uk/license.txt
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>
<?php $posts = $this->getPosts() ?>
<?php if (count($posts) > 0): ?>
	<div class="block block-blog block-recent-posts">
		<div class="block-content">
			<ul id="<?php echo $this->getListId() ?>">
			<?php foreach($posts as $post): ?>
				<li class="item">
                    <div>
                        <?php echo $this->htmlEscape($post->getPostDate()) ?>
                        <?php echo $this->htmlEscape($post->getPostAuthor()) ?>
                    </div>
                    <div>
                        <a href="<?php echo $post->getPermalink() ?>" title="<?php echo $this->htmlEscape($post->getPostTitle()) ?>"><?php echo $this->htmlEscape($post->getPostTitle()) ?></a>
                    </div>
                    <div>
                        <p>
                            <?php echo $this->htmlEscape($post->getPostContent()) ?>
                        </p>
                    </div>

				</li>
			<?php endforeach; ?>
			</ul>
			<script type="text/javascript">decorateList('<?php echo $this->getListId() ?>')</script>
		</div>
	</div>
<?php endif; ?>